### ISSUE TITLE
[chore]: add tests for updateNft action

### ISSUE THREAD

**Issue by thlorenz** [metaplex-foundation/js-next#24]
The `updateNft` action was added (https://github.com/metaplex-foundation/js-next/pull/18) but has not been tested yet which we'll need to fix.

**Comment by anoushk1234** [comment]
@brandontulsi the updateNft is giving is this error, is it something im doing wrong or is there an issue with the function
```ts
const { nft:createdNft } = await mx.nfts().createNft({
    name: 'On-chain NFT name',
    uri: metadataUri,
  });
const updatedImageFile = new MetaplexFile('updated_image', 'updated-image.jpg');
  const updatedImageUri: string = await mx.storage().upload(updatedImageFile);
  const updatedMetadataUri: string = await mx.storage().uploadJson<JsonMetadata>({
    name: 'Updated JSON NFT name',
    description: 'Updated JSON NFT description',
    image: updatedImageUri,
  });
const { nft: updated_nft }: { nft: Nft } = await mx.nfts().updateNft(createdNft, {
    name: 'Updated On-chain NFT name',
    uri: updatedMetadataUri,
  });
  ```
  
  
  ```
  not ok 85 Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x3b
  ---
    operator: error
    stack: |-
      Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x3b
          at Connection.sendEncodedTransaction (/Users/anoushkkharangate/Documents/js-next/node_modules/@solana/web3.js/lib/index.cjs.js:6929:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async Connection.sendRawTransaction (/Users/anoushkkharangate/Documents/js-next/node_modules/@solana/web3.js/lib/index.cjs.js:6890:20)
          at async Connection.sendTransaction (/Users/anoushkkharangate/Documents/js-next/node_modules/@solana/web3.js/lib/index.cjs.js:6880:12)
          
  ```
          
the issue seems to be in this line in nft client.ts
      
```ts
      const updateNftOutput = await this.metaplex.execute(operation, confirmOptions);
      
```

**Comment by lorisleiva** [comment]
Can you try to add `isMutable: true` when creating the NFT in your tests?

**Comment by anoushk1234** [comment]
Done with pr #38 , you can close this now
